apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-upload-pv-pod
spec:
  selector:
    matchLabels:
      app: image-upload-pv-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: image-upload-pv-pod
    spec:
      volumes:
        - name: image-upload-pv-storage
          persistentVolumeClaim:
            claimName: imageupload-pv-claim
      containers:
        - name: image-upload-pv-pod
          image: piyush9090/image-upload-logic:tagversion
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/app/uploads/images"
              name: image-upload-pv-storage          
          ports:
          - containerPort: 3000